# Generated by Django 2.2.1 on 2019-05-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Customer',
        ),
    ]
